### ISSUE TITLE
Add support for extensionless URLs

### ISSUE THREAD

**Issue by daveaglick** [natemcmaster/dotnet-serve#1]
This is valuable when serving files from static site generators which often use this pattern to create friendly URLs. Many web servers also support it (particularly those intended for static sites like GitHub Pages and Netlify), so this would bring dotnet-serve in line with the destination server if the site will eventually be served by one of those.

I propose the feature should be opt-in behind a CLI option `-e|--extensionless`.

My initial thoughts on implementation are that this would require creating and registering custom middleware. I already have a similar implementation of this feature for the local development server that ships with Wyam (https://github.com/Wyamio/Wyam/blob/develop/src/core/Wyam.Hosting/Owin/ExtensionlessUrlsMiddleware.cs), and it's architecture is pretty similar to this project, so I'm hoping a port wouldn't be too difficult.

**Comment by daveaglick** [comment]
FYI - I have a working prototype of this using a small custom middleware with no additional dependencies. I'll submit a PR tomorrow once I fix up the CLI options and polish it a little.

**Comment by natemcmaster** [comment]
So, naming is hard. I'm not sure yet about `-e|--extensionless`, but also not sure I have other great suggestions. Do you have other ideas? Other names I thought of:
`--pretty-urls`
`--clean-urls`
`--default-extension <EXT>` (allow multiple)

**Comment by daveaglick** [comment]
I really like the semantics of `--default-extensions` with the option to supply extensions or use .html and .htm as the default.
