### ISSUE TITLE
Add support for config as a file

### ISSUE THREAD

**Issue by natemcmaster** [natemcmaster/dotnet-serve#10]
Add support for configuring dotnet-serve options via file, so I don't have to keep remembering all the command line options I want to use.

Lookup:
 1. find file in cwd
 2. also lookup file in $HOME

TBD:
 format - JSON? provides nice intellisense in vscode
 filename? .dotnetserverc, serve.json dotnet-serve.json
 schema

**Comment by doggy8088** [comment]
Format: I vote for `JSON`.
Filename: I vote for `dotnet-serve.json`.

Also, I'd like to suggest to configure a **global** config file that can apply default `dotnet server` behavior.

**Comment by natemcmaster** [comment]
Closing. There appears to be little demand for this. It's a cool idea, but I have no plans to implement it.

**Comment by natemcmaster** [comment]
As the number of options grows, I think this will become necessary.

**Comment by natemcmaster** [comment]
Re-opening. I think this is worth doing, but may not have time myself. I think stale-bot was too aggressive here in closing this issue.

**Comment by mika76** [comment]
Is it not just easier to write a simple powershell script or bash script to start the server with the correct arguments?
