### ISSUE TITLE
[Question] Run the http server on specific port in the background and in every startup.

### ISSUE THREAD

**Issue by HamedFathi** [natemcmaster/dotnet-serve#100]
Hi Nate,

I need to have a site every time up and running so I need to run the server in the background (on a specific port) and also available in startup (or register as a windows service) when Windows starts.

Do you have any idea?

**Comment by natemcmaster** [comment]
A specific port can be specified as a command line argument (see the README). The part about running in the background seems like a generic Windows question, not really specific to this tool.
