### ISSUE TITLE
Add support for reverse proxy

### ISSUE THREAD

**Issue by doggy8088** [natemcmaster/dotnet-serve#11]
It can be useful to provide a proxy feature in the dotnet-serve that can serve some routes into another site to bypass Same-origin policy in the browser.

**Comment by natemcmaster** [comment]
I'm open to taking this as a PR. Feel free to let me know if you want to implement it.

**Comment by doggy8088** [comment]
@natemcmaster Is it suitable to integrate https://github.com/Azure/reverse-proxy-dotnet into this project?

**Comment by natemcmaster** [comment]
I'm not very familiar with that project.
I was hoping to use https://github.com/aspnet/proxy, but I don't know if
the latest released version of it works with .NET Core 2.1. It's still an
experimental middleware.

**Comment by doggy8088** [comment]
@natemcmaster In their samples, do you know why they are using [app.UseWebSockets()](https://github.com/aspnet/Proxy/blob/dev/samples/Microsoft.AspNetCore.Proxy.Samples/Startup.cs#L28) to run the proxy?  I don't understand what's the relationship between **WebSockets** and **Proxy**?

**Comment by doggy8088** [comment]
@natemcmaster For the command arguments/options, do you have any recommendation?

I prefer setting all the reverse proxy rules in the **dotnet-serve.json**-like file.  e.g.

```
{
  "/api/{*path}": {
    "target": "http://back.end/api/{path}",
  },
  "/{*path}": {
    "target": "https://back.end/index.html",
  }
}
```

What do you think?

**Comment by natemcmaster** [comment]
I’m currently thinking of supporting one proxy url to use as a fallback for
requests not satisfied by the local filesystem. So `--proxy <url>`.

Anything more than that seems like too much complexity. This tool isn’t
meant to replace writing your own ASP.NET Core. So I’m not convinced yet
that this should support routing and multiple proxies.   That’s not a “no”;
I’m just not convinced yet there are compelling scenarios for it. If you
think this is important, tell me more about what you need it for.

**Comment by doggy8088** [comment]
Let's keep it simple at first.  I'll find some time to implement this feature.  :)
