### ISSUE TITLE
.NET 6 enablement

### ISSUE THREAD

**Issue by lukemcdo** [natemcmaster/dotnet-serve#116]
I'll take a look at submitting something but this should probably be bumped to .NET 6 (and possibly left there until the next LTS). I think there's a way to target both 5 and 6 in a single project, which would probably be ideal.

**Comment by natemcmaster** [comment]
The project already compiles for .NET 6 https://github.com/natemcmaster/dotnet-serve/pull/103, so I don't think there is any action item here.
