### ISSUE TITLE
Compression is not working for dll files

### ISSUE THREAD

**Issue by albertwoo** [natemcmaster/dotnet-serve#121]
**Describe the bug**
I tried to use this to serve blazor web assembly files, but the compression is only for for css, html etc. But not for dll file.

**To Reproduce**
1. Create a empty blazor wasm project
2. Publish in release mode
3. Run dotnet-serve -b under the publish\wwwroot folder

**Expected behavior**

**Screenshots**
<img width="509" alt="image" src="https://user-images.githubusercontent.com/8017681/170164200-c6f1e29c-d55a-4d63-9a1f-2163ffc45d13.png">

**Comment by natemcmaster** [comment]
Feel free to make a pull request to extend the list. https://docs.microsoft.com/en-us/aspnet/core/performance/response-compression?view=aspnetcore-6.0#mime-types
