### ISSUE TITLE
-a switch to set the address is not working

### ISSUE THREAD

**Issue by lejsekt** [natemcmaster/dotnet-serve#132]
**Describe the bug**
The shorthand switch for "--address" - "-a" is not working.

**To Reproduce**
dotnet serve -a 0.0.0.0

Starting server, serving .
Listening on:
  http://localhost:35011

**Expected behavior**
I expect to be able reach the service on other interfaces than localhost, but only localhost works. Changing -a to --address fixes it.

Thank you.

**Comment by natemcmaster** [comment]
Closing as a duplicate of #131

**Comment by lejsekt** [comment]
I see, the -a switch indeed works with an IP address such as 10.x.y.z.
