### ISSUE TITLE
System.ArgumentException: An item with the same key has already been added. Key: Cross-Origin-Embedder-Policy

### ISSUE THREAD

**Issue by Jasonlhy** [natemcmaster/dotnet-serve#138]
**Describe the bug**
I want to add two headers so that SharedArrayBuffer can be enabled on the JavaScript side so I set up the .netconfig file as follow:

```
[serve]
    header = Cross-Origin-Embedder-Policy: require-corp
    header = Cross-Origin-Opener-Policy: same-origin
```

Sometimes it works, sometimes it doesn't work. Error message: System.ArgumentException: An item with the same key has already been added. Key: Cross-Origin-Embedder-Policy

**To Reproduce**
_Environment: Ubuntu 22_

1. Run `dotnet serve` 
2. Or run `dotnet serve --headers "Cross-Origin-Embedder-Policy:require-corp" --headers "Cross-Origin-Opener-Policy:same-origin"`

You can just test this repo in Github codespace:
https://github.com/Jasonlhy/emcc-playground

_Environment Windows 11_

1. Run `dotnet serve` is fine without facing any issues, it can also add the two headers
2. Run `dotnet serve --headers "Cross-Origin-Embedder-Policy:require-corp" --headers "Cross-Origin-Opener-Policy:same-origin"` will face the same issue

**Workaround**
Run `dotnet serve .netconfig` 

**Expected behavior**
Two headers should be added successfully without facing any error

**Screenshots**
![image](https://user-images.githubusercontent.com/1687930/210018136-576657bb-f812-43ef-bfea-e60306f94bda.png)

**Comment by natemcmaster** [comment]
None of the code in this project adds this header. Have you checked if there is something happening automatically in the ASP.NET Core framework itself? I did a quick search and see a few issues mentioning this header, https://github.com/dotnet/aspnetcore/search?q=Cross-Origin-Embedder-Policy&type=issues.
