### ISSUE TITLE
Enable setting open browser starting address

### ISSUE THREAD

**Issue by weitzhandler** [natemcmaster/dotnet-serve#141]
**Is your feature request related to a problem? Please describe.**
When using `dotnet-server -o`, enable setting the default path to navigate to.

**Describe the solution you'd like**
Add a `<PATH>` parameter to the -o arg, for example if the generated site is `http://localhost:62320/` and path is `main/index.html` it should navigate to `http://localhost:62320/main/index.html`.

Can PR if approved. Please let me know if I can change the open-browser arg to a string instead of boolean, and open root address if path not specified otherwise navigate to specified address.

**Comment by natemcmaster** [comment]
Is https://github.com/natemcmaster/dotnet-serve/pull/143 what you had in mind?

**Comment by weitzhandler** [comment]
Yes exactly, thank you for your effort @natemcmaster.
