### ISSUE TITLE
Add flag for compression level

### ISSUE THREAD

**Issue by onionhammer** [natemcmaster/dotnet-serve#146]
**Is your feature request related to a problem? Please describe.**
BrotliCompressionProviderOptions has a 'Level' property, but the provider used in dotnet-serve can only provide the default option

**Describe the solution you'd like**

Add a "--compression-level" flag (or something to that effect) which parses as System.IO.Compression.CompressionLevel enum

**Comment by natemcmaster** [comment]
I would accept a PR which adds this feature.
