### ISSUE TITLE
Support for referencing in other projects

### ISSUE THREAD

**Issue by wkallhof** [natemcmaster/dotnet-serve#15]
I am building a static site generator and was hoping to leverage dotnet-serve to server the static site.

The .NET Core Tools space is a little new to me, but I was either hoping I could do one of two things:
1. Reference your tool via `<DotNetCliToolReference Include="dotnet-serve" Version="1.0.0" />`
     - I assume that these Tool References are for local development only and do not get packaged with the output of your application. Is that correct? This probably wouldn't solve my problem.
2. Reference the actual NuGet package as a `PackageReference` and utilize your `SimpleServer` directly. Since I am also using `CommandLineUtils`, possible reference your command directly as a sub command of my application? 

Either solution results in the following cryptic error : 
```
XX.csproj : error NU1202: Package dotnet-serve 1.0.0 is not compatible with netcoreapp2.1 (.NETCoreApp,Version=v2.1). Package dotnet-serve 1.0.0 supports: netcoreapp2.1 (.NETCoreApp,Version=v2.1) / any

XX.csproj : error NU1212: Invalid project-package combination for dotnet-serve 1.0.0. DotnetToolReference project style can only contain references of the DotnetTool type
```

The first error, as I read it, contradicts itself. I am building a .NET Core 2.1 app.

Thoughts?

**Comment by natemcmaster** [comment]
I didn't really intend for this project to become a class library. I don't really want to commit to making the `SimpleServer` class available as an API, but this is open source so you're welcome to copy my code. All I ask is you copy-left (i.e. leave the copyright header and add a comment such as "this code came from https://github.com/natemcmaster/dotnet-serve/blob/0617afd0f52bcfed2eb3e6b46dd9e05b07c5e51c/src/dotnet-serve/SimpleServer.cs"
