### ISSUE TITLE
Add file extension MIME type mapping

### ISSUE THREAD

**Issue by Tarmil** [natemcmaster/dotnet-serve#16]
It would be nice to be able to indicate a custom mapping from file extension to MIME type. My current use case is WebAssembly: the browser refuses to load a wasm module if the MIME type isn't "application/wasm".

Maybe with a syntax like this:

    dotnet serve --mime .wasm=application/wasm

**Comment by natemcmaster** [comment]
LGTM. Let's make a 1.1 release for this.
