### ISSUE TITLE
Add support for setting headers

### ISSUE THREAD

**Issue by andrewlock** [natemcmaster/dotnet-serve#18]
Hi Nate,

First off - thanks for this tool, I use it regularly to serve static file sites. 

One feature I found a need for recently was to set response headers. It was specifically CSP headers, but I think this should generalise to all response headers.

I was thinking you could set the response headers either using command line switches, or via a file (e.g. [something like this](https://www.netlify.com/docs/headers-and-basic-auth/#custom-headers), but probably just apply to all paths?)

What do you reckon?

**Comment by natemcmaster** [comment]
A command line switch is a good start. I’d take a PR for that. Something like `--header Key=Value`.

I’ve considered adding a config file. As the number of options grows, I think this will be necessary. See 
https://github.com/natemcmaster/dotnet-serve/issues/10. If you want to help with that issue too, I’d be grateful.

**Comment by andrewlock** [comment]
Sounds good to me, I'll take a look at the command line switches to start, then will maybe get to #10 later.

**Comment by natemcmaster** [comment]
Merged in https://github.com/natemcmaster/dotnet-serve/pull/21.
