### ISSUE TITLE
add support for options request

### ISSUE THREAD

**Issue by WeihanLi** [natemcmaster/dotnet-serve#22]
please add support for options request

when I send a options request, I got a 404 returned.
when I send a GET request, it works.

![image](https://user-images.githubusercontent.com/7604648/50949868-dded6d80-14e2-11e9-87d3-6efb627feb13.png)

**Comment by natemcmaster** [comment]
I would accept a PR which adds support for this, but I'm probably not going to do it myself.

**Comment by natemcmaster** [comment]
Re-opening. I think this is worth doing, but may not have time myself. I think stale bot was too aggressive here in closing this issue.

**Comment by ansariabr** [comment]
Hi @natemcmaster, seems like **good-first-issue**. I am working on this, will raise a PR once done.

**Comment by natemcmaster** [comment]
Thanks for the contribution @ansariabr! 

Resolved with #45
