### ISSUE TITLE
System.TypeLoadException: Method 'GetFallbackPolicyAsync' ... does not have an implementation

### ISSUE THREAD

**Issue by mungojam** [natemcmaster/dotnet-serve#26]
I'm getting this when trying to run `dotnet serve` using .net core 3.0 rc1

> System.TypeLoadException: Method 'GetFallbackPolicyAsync' in type 'McMaster.DotNet.Serve.NullAuthPolicyProvider' from assembly 'dotnet-serve, Version=1.3.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation
> 
>  at McMaster.DotNet.Serve.Startup.ConfigureServices(IServiceCollection services)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)

> dotnet --version
> 3.0.100-rc1-014190

https://github.com/googleapis/google-api-dotnet-client/issues/1434#issuecomment-527104967 is a possible fix or workaround but needs to be done in the library itself I think

**Comment by natemcmaster** [comment]
Looks like I’ll have to cross compile this app for .NET Core 3.0. It’s regrettably unavoidable. AspNetCore made breaking changes... :-/

**Comment by natemcmaster** [comment]
b0e61afc63f40df2443a45daa30ea00416b2e477

Will be released as 1.4.0 later tonight.

**Comment by mungojam** [comment]
Great, thanks for the speedy turnaround 🙂
