### ISSUE TITLE
End with proper error exit codes 

### ISSUE THREAD

**Issue by valerysntx** [natemcmaster/dotnet-serve#4]
From any error state, please return more adequate error codes to OS, this is really helpful for automation tasks
 E.g. https://msdn.microsoft.com/en-us/library/ms681382(v=vs.85),

**Comment by valerysntx** [comment]
private const int ERROR = 2;

**Comment by natemcmaster** [comment]
PR's gladly accepted, please and thank you :)

**Comment by natemcmaster** [comment]
Closing as this bug is stale. I would still consider a PR for this, but I have not plans to make changes here.
