### ISSUE TITLE
Ambiguous certificate match

### ISSUE THREAD

**Issue by TFTomSun** [natemcmaster/dotnet-serve#57]
**Describe the bug**
When I try to use dotnet serve 
```
dotnet serve -o -S -p 44444 -d publish
```

i get the following output
```
Failed to configure the HTTPS. Ambiguous certficiate match. Multiple certificates found with extension '1.3.6.1.4.1.311.84.1.1' (ASP.NET Core HTTPS development certificate). 

```
Do you have an idea what could be the root cause or how it can be fixed?

**Comment by natemcmaster** [comment]
Probably means you have an old or expired aspnetcore dev cert installed. You can either uninstall the old certs with "dotnet dev-certs https --clean" (I think?) And/or we can make this code more robust https://github.com/natemcmaster/dotnet-serve/blob/5c76d38f29ffa491c2b6fa9b9c29964ec69ce282/src/dotnet-serve/Security/CertificateLoader.cs#L160

**Comment by ansariabr** [comment]
What is the expected fix for this @natemcmaster, I can take this up.

**Comment by natemcmaster** [comment]
If CertificateLoader finds multiple certificates with extension '1.3.6.1.4.1.311.84.1.1', choose one. Probably best to choose the newest one. Don’t pick an expired one.

**Comment by natemcmaster** [comment]
This is released in https://www.nuget.org/packages/dotnet-serve/1.7.131
