### ISSUE TITLE
0.0.0.0 doesn't work on Windows

### ISSUE THREAD

**Issue by shanselman** [natemcmaster/dotnet-serve#6]
0.0.0.0 doesn't work on Windows

**Comment by natemcmaster** [comment]
It's more commonly use on macOS and Windows and is the equivalent of `System.Net.IPAddress.Any`, i.e. bind to any network interface on the local machine. In 0.2.1, I updated `--open-browser` to translate IPAny to "localhost" and open that instead.

https://www.nuget.org/packages/dotnet-serve/0.2.1
