### ISSUE TITLE
iam trying to start two kafka cluster to make a replication but i get error

### ISSUE THREAD

**Issue by alaasaeedradwan** [natemcmaster/dotnet-serve#62]
Iam trying to start two kafka cluster to make a replication and I start zookeeper and kafka for the first cluster , and start zookeeper for the second cluster but when iam getting to start kafka for the second cluster i get that error .
 ERROR [KafkaServer id=0] Fatal error during KafkaServer startup. Prepare to shutdown (kafka.server.KafkaServer)
java.lang.RuntimeException: java.io.IOException: Failed to bind to /0.0.0.0:8090

**Comment by natemcmaster** [comment]
This project has nothing to do with Kafka.
