### ISSUE TITLE
[Question] How do we know what's in each release?

### ISSUE THREAD

**Issue by adamralph** [natemcmaster/dotnet-serve#82]
Several releases have been made today, but I can't see any way to see what each of them contains (other than diffing the tagged commits of course).

**Comment by natemcmaster** [comment]
You already said it -- git log. GitHub also offers helpful UI like this. These days, the updates are mostly automated by dependabot as this project is in maintenance mode and has no feature requests.

![image](https://user-images.githubusercontent.com/2696087/110249388-ca0aee00-7f2a-11eb-8953-e3ec8b618409.png)
