### ISSUE TITLE
[Question] Is there a way to override arbitrary kestrel options

### ISSUE THREAD

**Issue by mungojam** [natemcmaster/dotnet-serve#84]
I've got a site that relies on very long URL strings, so I'd like to increase the default `maxQueryString` config option in kestrel. I believe this would usually be done in the web.config, but I guess we don't have a way to override that in dotnet serve. Any ideas or tricks to achieve the same?

I'm using dotnet serve to self-host a react site so that I can look into a production issue with a profile build. It's really handy :)

**Comment by natemcmaster** [comment]
All supported options are listed in the readme.md file. maxQueryString is not currently one of them.

 If you would like to make that a new command line argument, feel free to propose the use case. Pull requests are also highly recommended. This project is basically in maintenance mode. I don't do feature work myself here anymore.
