### ISSUE TITLE
[Question] .netconfig storing wrong path?

### ISSUE THREAD

**Issue by granicz** [natemcmaster/dotnet-serve#91]
When I use the `--save-options` flag, `.netconfig` will save the folder I specified with `-d` verbatim. But I wonder, why not save the path of the given folder relative to the config file itself? This way, with a tiny bit of extra work, `dotnet serve` could be invoked from anywhere in the source tree.

**Comment by natemcmaster** [comment]
I would be okay with taking a change that makes the file path relative in the saved config file. Feel free to submit a pull request for this.

**Comment by lohithgn** [comment]
@granicz  can you explain a bit more of the usage. 
Lets assume you have folders `fold1/fold2/fold3` 
You are in `fold1` now. 
you want to server `fold3`. 
you would do `dotnet serve -d fold2/fold3` - are you saying .netconfig should be saved in fold1 with relative path for fold3. 
?

**Comment by lohithgn** [comment]
@granicz my bad. I mis-understood what you were trying to say. I now see what you are hinting at. 

for the first time, if you do `dotnet server --directory fold2/fold3 --save-options` - it is now storing `fold2/fold3`. 
What you are saying is - it needs to be `./fold2/fold3`. is the understanding correct ?
