### ISSUE TITLE
Running with .NET 6.0 RC1 - on an Apple M1: Nothing happens

### ISSUE THREAD

**Issue by ChristianWeyer** [natemcmaster/dotnet-serve#99]
Alright: I have a MBP with an Apple M1.
I am running .NET 6 RC1 for ARM.

After installing `dotnet-serve` and trying to run it in a folder, just nothing happens.

Can anybody confirm this behavior?

https://user-images.githubusercontent.com/888718/134773577-1f202ba3-4cba-4bd4-96e0-83a65b5031a7.mov

Thanks!

**Comment by natemcmaster** [comment]
I don't have an M1 mac to confirm. I would recommend reporting to https://github.com/dotnet/runtime. I've seen similar issues such as https://github.com/dotnet/runtime/issues/52335 (Not sure if the issue is exactly the same...but it's worth reporting to MIcrosoft anyways.)

**Comment by natemcmaster** [comment]
Possible root cause https://github.com/dotnet/sdk/issues/21349
